CREATE TABLE deslocamentos(
   id_pessoas     INTEGER  NOT NULL PRIMARY KEY 
  ,d_setor        VARCHAR(45)
  ,d_seq          INTEGER 
  ,d_num_entr     INTEGER 
  ,d_num_pess     VARCHAR(45)
  ,origem_zona    INTEGER 
  ,hora_saida     VARCHAR(45)
  ,d_tela         INTEGER 
  ,d_zona         INTEGER 
  ,origem_local   INTEGER 
  ,origem_motivo  INTEGER 
  ,destino_local  INTEGER 
  ,destino_zona   INTEGER 
  ,destino_motivo INTEGER 
  ,hora_chegada   VARCHAR(45)
  ,modo_trans     INTEGER 
  ,tmp_o_ape      VARCHAR(45)
  ,tmp_o_esp      VARCHAR(45)
  ,tmp_d_ape      VARCHAR(45)
  ,d_form_pag     INTEGER 
  ,d_val_pass     VARCHAR(45)
  ,d_estacion     INTEGER 
  ,d_val_esta     VARCHAR(45)
  ,d_mud_hab      VARCHAR(45)
  ,fexp_fam       VARCHAR(45)
  ,fexp_pess      VARCHAR(45)
  ,fexp_ger       VARCHAR(45)
  ,periodo        VARCHAR(45)
  ,cont_orig      VARCHAR(45)
  ,modo_princ     VARCHAR(45)
  ,macro_ori      VARCHAR(45)
  ,zn_orig        INTEGER 
  ,motivo_ori     INTEGER 
  ,hora_orig      VARCHAR(45)
  ,macro_des      VARCHAR(45)
  ,zn_dest        INTEGER 
  ,motivo_dest    INTEGER 
  ,hor_dest       VARCHAR(45)
  ,tmp_viagem     VARCHAR(45)
  ,tmp_ape        VARCHAR(45)
  ,tmp_esp        VARCHAR(45)
  ,exp_tp_via     VARCHAR(45)
  ,exp_tp_ape     VARCHAR(45)
  ,exp_tp_esp     VARCHAR(45)
  ,per_cheg       VARCHAR(45)
  ,agregado_01    VARCHAR(45)
);